var qs4_dict = 
{
    "Someone is immediately available to me that will protect me if I feel I need it": 1,
    "I trust that my personal belongings will be where I left them when I return": 1,
    "I feel sick, or tight in my jaw, neck, chest, or back": -1,
    "I feel like I need to defend myself": -1,
    "I feel safe": 1,
    "I usually know what will happen in my day": 1,
    "I sleep in the same room each night": 1,
    "I have had to move homes unexpectedly": -1,
    "I am able to lock a door at night when I sleep": 1,
    "I know how people around me will respond if I do something that will hurt me or someone else": 1,
    "I feel safe at home": 1,
    "I fall asleep completely": 1,
    "It takes me a long time to fall all the way to sleep": -1,
    "I have confidence that I am safe at home": 1, 
    "People make me feel bad about myself, shame, humilate, or embarrass me": -1,
    "I check the door of my home or room to make sure it is locked or no one is coming in?": -1,
    "Family members or guests take my personal items without my consent": -1,
    "Family members or guests publically embarrass me in my home": -1,
    "I would feel safe introducing my family to a new friend or coworker": 1,
    "Family members or guests yell in my home": -1,
    "Family members or guests slap, punch, hit or kick walls, doors or other items in my home": -1,
    "The television or music is turned up loud in my home to be heard over my family's voices": -1,
    "Family members or guests slap, punch, hit or kick me, other family members or guests in my home": -1,
    "There is a gun in my home that can be easily accessed by family members and guests": -1,
    "A family member or guest has accessed or threatened to access a gun for purposes other than hunting or safety in my home": -1,
    "Family members or guests do drugs in my home": -1,
    "Family members or guests consume large amounts of alcohol in my home": -1,
    "Drugs or large amounts of alcohol are consumed daily in my home": -1,
    "Sexual abuse occurrs in my home": -1,
    "I have a place to live in that will always be there for me if I need it": 1,
    "When I leave home (for school or other activities) I trust that I will be able to enter that same home when I return": 1,
    "When I leave my home, I trust that when I return my personal possessions will be there": 1,
    "When you leave my home I trust that my possessions will be in relatively the same location as when I left": 1,
    "I stay in a house for one year or less": -1,
    "I am afraid or anxious to leave my residence because I don’t trust I can return to my it or my belongings": -1
}
export default qs4_dict;